/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SystemConfigService } from "../systemConfig.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SystemConfigCreateInput } from "./SystemConfigCreateInput";
import { SystemConfig } from "./SystemConfig";
import { SystemConfigFindManyArgs } from "./SystemConfigFindManyArgs";
import { SystemConfigWhereUniqueInput } from "./SystemConfigWhereUniqueInput";
import { SystemConfigUpdateInput } from "./SystemConfigUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SystemConfigControllerBase {
  constructor(
    protected readonly service: SystemConfigService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SystemConfig })
  @nestAccessControl.UseRoles({
    resource: "SystemConfig",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSystemConfig(
    @common.Body() data: SystemConfigCreateInput
  ): Promise<SystemConfig> {
    return await this.service.createSystemConfig({
      data: data,
      select: {
        createdAt: true,
        defaultTimeout: true,
        id: true,
        maxUsers: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SystemConfig] })
  @ApiNestedQuery(SystemConfigFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SystemConfig",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async systemConfigs(@common.Req() request: Request): Promise<SystemConfig[]> {
    const args = plainToClass(SystemConfigFindManyArgs, request.query);
    return this.service.systemConfigs({
      ...args,
      select: {
        createdAt: true,
        defaultTimeout: true,
        id: true,
        maxUsers: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SystemConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SystemConfig",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async systemConfig(
    @common.Param() params: SystemConfigWhereUniqueInput
  ): Promise<SystemConfig | null> {
    const result = await this.service.systemConfig({
      where: params,
      select: {
        createdAt: true,
        defaultTimeout: true,
        id: true,
        maxUsers: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SystemConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SystemConfig",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSystemConfig(
    @common.Param() params: SystemConfigWhereUniqueInput,
    @common.Body() data: SystemConfigUpdateInput
  ): Promise<SystemConfig | null> {
    try {
      return await this.service.updateSystemConfig({
        where: params,
        data: data,
        select: {
          createdAt: true,
          defaultTimeout: true,
          id: true,
          maxUsers: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SystemConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SystemConfig",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSystemConfig(
    @common.Param() params: SystemConfigWhereUniqueInput
  ): Promise<SystemConfig | null> {
    try {
      return await this.service.deleteSystemConfig({
        where: params,
        select: {
          createdAt: true,
          defaultTimeout: true,
          id: true,
          maxUsers: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
