/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProxiesService } from "../proxies.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProxiesCreateInput } from "./ProxiesCreateInput";
import { Proxies } from "./Proxies";
import { ProxiesFindManyArgs } from "./ProxiesFindManyArgs";
import { ProxiesWhereUniqueInput } from "./ProxiesWhereUniqueInput";
import { ProxiesUpdateInput } from "./ProxiesUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProxiesControllerBase {
  constructor(
    protected readonly service: ProxiesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Proxies })
  @nestAccessControl.UseRoles({
    resource: "Proxies",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProxies(
    @common.Body() data: ProxiesCreateInput
  ): Promise<Proxies> {
    return await this.service.createProxies({
      data: data,
      select: {
        createdAt: true,
        id: true,
        ipAddress: true,
        port: true,
        proxyAddress: true,
        proxyLogin: true,
        proxyPassword: true,
        proxyPort: true,
        proxyType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Proxies] })
  @ApiNestedQuery(ProxiesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Proxies",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proxiesItems(@common.Req() request: Request): Promise<Proxies[]> {
    const args = plainToClass(ProxiesFindManyArgs, request.query);
    return this.service.proxiesItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        ipAddress: true,
        port: true,
        proxyAddress: true,
        proxyLogin: true,
        proxyPassword: true,
        proxyPort: true,
        proxyType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Proxies })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Proxies",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proxies(
    @common.Param() params: ProxiesWhereUniqueInput
  ): Promise<Proxies | null> {
    const result = await this.service.proxies({
      where: params,
      select: {
        createdAt: true,
        id: true,
        ipAddress: true,
        port: true,
        proxyAddress: true,
        proxyLogin: true,
        proxyPassword: true,
        proxyPort: true,
        proxyType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Proxies })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Proxies",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProxies(
    @common.Param() params: ProxiesWhereUniqueInput,
    @common.Body() data: ProxiesUpdateInput
  ): Promise<Proxies | null> {
    try {
      return await this.service.updateProxies({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          ipAddress: true,
          port: true,
          proxyAddress: true,
          proxyLogin: true,
          proxyPassword: true,
          proxyPort: true,
          proxyType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Proxies })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Proxies",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProxies(
    @common.Param() params: ProxiesWhereUniqueInput
  ): Promise<Proxies | null> {
    try {
      return await this.service.deleteProxies({
        where: params,
        select: {
          createdAt: true,
          id: true,
          ipAddress: true,
          port: true,
          proxyAddress: true,
          proxyLogin: true,
          proxyPassword: true,
          proxyPort: true,
          proxyType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
